version: "3.9"
services:
  # run with docker-compose up
  db:
    image: postgres:14.2-alpine
    restart: always
    container_name: "lc_postgres"  # provides the container name
    environment:
      POSTGRES_USER: coder
      POSTGRES_PASSWORD: codes
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/leetcode/data
#      - ./db/leetcode_db_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  default:
    name: leetcode