version: "3.9"
services:
  # run with docker-compose up
  db:
    image: postgres:14.2-alpine
    restart: always
    container_name: "prep_postgres"  # provides the container name
    environment:
      POSTGRES_USER: coder
      POSTGRES_PASSWORD: codes
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/leetcode/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 3

  api:
    container_name: "notes_api"
    environment:
      DB_HOST: db
      DB_NAME: prep
      DB_USER: coder
      DB_PASSWORD: codes
      DB_PORT: 5432
      LISTEN_PORT: ":80"
    ports:
      - "8083:80"
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    command: ./bin/api

  etl:
    container_name: "pg_etl"
    environment:
      API_ENV: ci
      DB_ENV_PREFIX: DB
      DB_HOST: db
      DB_NAME: prep
      DB_USER: coder
      DB_PASSWORD: codes
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/py/Dockerfile
      target: etl
    command: >
      sh -c "make database-data-load
      && touch ./finished.txt"

networks:
  default:
    name: leetcode