// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: rpc/v1/notes.proto

package v1

import (
	v1 "github.com/Ydot19/ti-prep/codegen/go/model/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProblemCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetProblemCategoriesRequest) Reset() {
	*x = GetProblemCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProblemCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemCategoriesRequest) ProtoMessage() {}

func (x *GetProblemCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetProblemCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{0}
}

func (x *GetProblemCategoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetProblemCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details *v1.Category `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *GetProblemCategoriesResponse) Reset() {
	*x = GetProblemCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProblemCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemCategoriesResponse) ProtoMessage() {}

func (x *GetProblemCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetProblemCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{1}
}

func (x *GetProblemCategoriesResponse) GetDetails() *v1.Category {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetProblemsByCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaginationStart int32 `protobuf:"varint,1,opt,name=pagination_start,json=paginationStart,proto3" json:"pagination_start,omitempty"`
	PaginationEnd   int32 `protobuf:"varint,2,opt,name=pagination_end,json=paginationEnd,proto3" json:"pagination_end,omitempty"`
}

func (x *GetProblemsByCategoryRequest) Reset() {
	*x = GetProblemsByCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProblemsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemsByCategoryRequest) ProtoMessage() {}

func (x *GetProblemsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetProblemsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{2}
}

func (x *GetProblemsByCategoryRequest) GetPaginationStart() int32 {
	if x != nil {
		return x.PaginationStart
	}
	return 0
}

func (x *GetProblemsByCategoryRequest) GetPaginationEnd() int32 {
	if x != nil {
		return x.PaginationEnd
	}
	return 0
}

type GetProblemsByCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details []*v1.Problem `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *GetProblemsByCategoryResponse) Reset() {
	*x = GetProblemsByCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProblemsByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemsByCategoryResponse) ProtoMessage() {}

func (x *GetProblemsByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemsByCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetProblemsByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{3}
}

func (x *GetProblemsByCategoryResponse) GetDetails() []*v1.Problem {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetProblemByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetProblemByIdRequest) Reset() {
	*x = GetProblemByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProblemByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemByIdRequest) ProtoMessage() {}

func (x *GetProblemByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemByIdRequest.ProtoReflect.Descriptor instead.
func (*GetProblemByIdRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{4}
}

func (x *GetProblemByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProblemByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details           *v1.Problem `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	NoteIds           []string    `protobuf:"bytes,2,rep,name=note_ids,json=noteIds,proto3" json:"note_ids,omitempty"`
	ImplementationIds []string    `protobuf:"bytes,3,rep,name=implementation_ids,json=implementationIds,proto3" json:"implementation_ids,omitempty"`
}

func (x *GetProblemByIdResponse) Reset() {
	*x = GetProblemByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProblemByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemByIdResponse) ProtoMessage() {}

func (x *GetProblemByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemByIdResponse.ProtoReflect.Descriptor instead.
func (*GetProblemByIdResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{5}
}

func (x *GetProblemByIdResponse) GetDetails() *v1.Problem {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *GetProblemByIdResponse) GetNoteIds() []string {
	if x != nil {
		return x.NoteIds
	}
	return nil
}

func (x *GetProblemByIdResponse) GetImplementationIds() []string {
	if x != nil {
		return x.ImplementationIds
	}
	return nil
}

type GetProblemNotesByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetProblemNotesByIdRequest) Reset() {
	*x = GetProblemNotesByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProblemNotesByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemNotesByIdRequest) ProtoMessage() {}

func (x *GetProblemNotesByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemNotesByIdRequest.ProtoReflect.Descriptor instead.
func (*GetProblemNotesByIdRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{6}
}

type GetProblemNotesByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetProblemNotesByIdResponse) Reset() {
	*x = GetProblemNotesByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProblemNotesByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemNotesByIdResponse) ProtoMessage() {}

func (x *GetProblemNotesByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemNotesByIdResponse.ProtoReflect.Descriptor instead.
func (*GetProblemNotesByIdResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{7}
}

type GetImplementationNotesByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetImplementationNotesByIdRequest) Reset() {
	*x = GetImplementationNotesByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImplementationNotesByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImplementationNotesByIdRequest) ProtoMessage() {}

func (x *GetImplementationNotesByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImplementationNotesByIdRequest.ProtoReflect.Descriptor instead.
func (*GetImplementationNotesByIdRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{8}
}

type GetImplementationNotesByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetImplementationNotesByIdResponse) Reset() {
	*x = GetImplementationNotesByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImplementationNotesByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImplementationNotesByIdResponse) ProtoMessage() {}

func (x *GetImplementationNotesByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImplementationNotesByIdResponse.ProtoReflect.Descriptor instead.
func (*GetImplementationNotesByIdResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{9}
}

type CreateOrUpdateProblemDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrUpdateProblemDetailsRequest) Reset() {
	*x = CreateOrUpdateProblemDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateProblemDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateProblemDetailsRequest) ProtoMessage() {}

func (x *CreateOrUpdateProblemDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateProblemDetailsRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateProblemDetailsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{10}
}

type CreateOrUpdateProblemDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrUpdateProblemDetailsResponse) Reset() {
	*x = CreateOrUpdateProblemDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateProblemDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateProblemDetailsResponse) ProtoMessage() {}

func (x *CreateOrUpdateProblemDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateProblemDetailsResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateProblemDetailsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{11}
}

type CreateOrUpdateProblemNotesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrUpdateProblemNotesRequest) Reset() {
	*x = CreateOrUpdateProblemNotesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateProblemNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateProblemNotesRequest) ProtoMessage() {}

func (x *CreateOrUpdateProblemNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateProblemNotesRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateProblemNotesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{12}
}

type CreateOrUpdateProblemNotesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrUpdateProblemNotesResponse) Reset() {
	*x = CreateOrUpdateProblemNotesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateProblemNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateProblemNotesResponse) ProtoMessage() {}

func (x *CreateOrUpdateProblemNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateProblemNotesResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateProblemNotesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{13}
}

type GetAlgorithmCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAlgorithmCategoriesRequest) Reset() {
	*x = GetAlgorithmCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlgorithmCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlgorithmCategoriesRequest) ProtoMessage() {}

func (x *GetAlgorithmCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlgorithmCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetAlgorithmCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{14}
}

type GetAlgorithmCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAlgorithmCategoriesResponse) Reset() {
	*x = GetAlgorithmCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlgorithmCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlgorithmCategoriesResponse) ProtoMessage() {}

func (x *GetAlgorithmCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlgorithmCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetAlgorithmCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{15}
}

type GetAlgorithmsByCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAlgorithmsByCategoryRequest) Reset() {
	*x = GetAlgorithmsByCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlgorithmsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlgorithmsByCategoryRequest) ProtoMessage() {}

func (x *GetAlgorithmsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlgorithmsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetAlgorithmsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{16}
}

type GetAlgorithmsByCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAlgorithmsByCategoryResponse) Reset() {
	*x = GetAlgorithmsByCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlgorithmsByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlgorithmsByCategoryResponse) ProtoMessage() {}

func (x *GetAlgorithmsByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlgorithmsByCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetAlgorithmsByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{17}
}

type CreateOrUpdateAlgorithmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrUpdateAlgorithmRequest) Reset() {
	*x = CreateOrUpdateAlgorithmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateAlgorithmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateAlgorithmRequest) ProtoMessage() {}

func (x *CreateOrUpdateAlgorithmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateAlgorithmRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateAlgorithmRequest) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{18}
}

type CreateOrUpdateAlgorithmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrUpdateAlgorithmResponse) Reset() {
	*x = CreateOrUpdateAlgorithmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_v1_notes_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateAlgorithmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateAlgorithmResponse) ProtoMessage() {}

func (x *CreateOrUpdateAlgorithmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_v1_notes_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateAlgorithmResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateAlgorithmResponse) Descriptor() ([]byte, []int) {
	return file_rpc_v1_notes_proto_rawDescGZIP(), []int{19}
}

var File_rpc_v1_notes_proto protoreflect.FileDescriptor

var file_rpc_v1_notes_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x16, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x33, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x49, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x62, 0x6c, 0x65, 0x6d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x22, 0x70, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x73,
	0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x0e,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x6e, 0x64, 0x22, 0x49, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x27,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x11, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x62, 0x6c, 0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x49,
	0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74,
	0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25,
	0x0a, 0x23, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x24, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a,
	0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x24, 0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x0a, 0x1e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x73, 0x42, 0x79, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x21, 0x0a,
	0x1f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x73, 0x42, 0x79,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x20, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x21, 0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x86, 0x08, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x62, 0x6c, 0x65, 0x6d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x20,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x21,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x73,
	0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x65,
	0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4e, 0x6f, 0x74,
	0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x6f, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x12, 0x26,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x74, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x75, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x28, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6f, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x26, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x22, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x67,
	0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x66,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x73, 0x42,
	0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x23, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x73, 0x42, 0x79, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x73, 0x42, 0x79, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x12, 0x23, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c, 0x67, 0x6f, 0x72,
	0x69, 0x74, 0x68, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x59, 0x64, 0x6f,
	0x74, 0x31, 0x39, 0x2f, 0x74, 0x69, 0x2d, 0x70, 0x72, 0x65, 0x70, 0x2f, 0x63, 0x6f, 0x64, 0x65,
	0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_v1_notes_proto_rawDescOnce sync.Once
	file_rpc_v1_notes_proto_rawDescData = file_rpc_v1_notes_proto_rawDesc
)

func file_rpc_v1_notes_proto_rawDescGZIP() []byte {
	file_rpc_v1_notes_proto_rawDescOnce.Do(func() {
		file_rpc_v1_notes_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_v1_notes_proto_rawDescData)
	})
	return file_rpc_v1_notes_proto_rawDescData
}

var file_rpc_v1_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_rpc_v1_notes_proto_goTypes = []interface{}{
	(*GetProblemCategoriesRequest)(nil),          // 0: rpc.GetProblemCategoriesRequest
	(*GetProblemCategoriesResponse)(nil),         // 1: rpc.GetProblemCategoriesResponse
	(*GetProblemsByCategoryRequest)(nil),         // 2: rpc.GetProblemsByCategoryRequest
	(*GetProblemsByCategoryResponse)(nil),        // 3: rpc.GetProblemsByCategoryResponse
	(*GetProblemByIdRequest)(nil),                // 4: rpc.GetProblemByIdRequest
	(*GetProblemByIdResponse)(nil),               // 5: rpc.GetProblemByIdResponse
	(*GetProblemNotesByIdRequest)(nil),           // 6: rpc.GetProblemNotesByIdRequest
	(*GetProblemNotesByIdResponse)(nil),          // 7: rpc.GetProblemNotesByIdResponse
	(*GetImplementationNotesByIdRequest)(nil),    // 8: rpc.GetImplementationNotesByIdRequest
	(*GetImplementationNotesByIdResponse)(nil),   // 9: rpc.GetImplementationNotesByIdResponse
	(*CreateOrUpdateProblemDetailsRequest)(nil),  // 10: rpc.CreateOrUpdateProblemDetailsRequest
	(*CreateOrUpdateProblemDetailsResponse)(nil), // 11: rpc.CreateOrUpdateProblemDetailsResponse
	(*CreateOrUpdateProblemNotesRequest)(nil),    // 12: rpc.CreateOrUpdateProblemNotesRequest
	(*CreateOrUpdateProblemNotesResponse)(nil),   // 13: rpc.CreateOrUpdateProblemNotesResponse
	(*GetAlgorithmCategoriesRequest)(nil),        // 14: rpc.GetAlgorithmCategoriesRequest
	(*GetAlgorithmCategoriesResponse)(nil),       // 15: rpc.GetAlgorithmCategoriesResponse
	(*GetAlgorithmsByCategoryRequest)(nil),       // 16: rpc.GetAlgorithmsByCategoryRequest
	(*GetAlgorithmsByCategoryResponse)(nil),      // 17: rpc.GetAlgorithmsByCategoryResponse
	(*CreateOrUpdateAlgorithmRequest)(nil),       // 18: rpc.CreateOrUpdateAlgorithmRequest
	(*CreateOrUpdateAlgorithmResponse)(nil),      // 19: rpc.CreateOrUpdateAlgorithmResponse
	(*v1.Category)(nil),                          // 20: model.Category
	(*v1.Problem)(nil),                           // 21: model.Problem
}
var file_rpc_v1_notes_proto_depIdxs = []int32{
	20, // 0: rpc.GetProblemCategoriesResponse.details:type_name -> model.Category
	21, // 1: rpc.GetProblemsByCategoryResponse.details:type_name -> model.Problem
	21, // 2: rpc.GetProblemByIdResponse.details:type_name -> model.Problem
	0,  // 3: rpc.NotesService.GetProblemCategories:input_type -> rpc.GetProblemCategoriesRequest
	2,  // 4: rpc.NotesService.GetProblemsByCategory:input_type -> rpc.GetProblemsByCategoryRequest
	4,  // 5: rpc.NotesService.GetProblemById:input_type -> rpc.GetProblemByIdRequest
	6,  // 6: rpc.NotesService.GetProblemNotesById:input_type -> rpc.GetProblemNotesByIdRequest
	8,  // 7: rpc.NotesService.GetImplementationNotesById:input_type -> rpc.GetImplementationNotesByIdRequest
	10, // 8: rpc.NotesService.CreateOrUpdateProblemDetails:input_type -> rpc.CreateOrUpdateProblemDetailsRequest
	12, // 9: rpc.NotesService.CreateOrUpdateProblemNotes:input_type -> rpc.CreateOrUpdateProblemNotesRequest
	14, // 10: rpc.NotesService.GetAlgorithmCategories:input_type -> rpc.GetAlgorithmCategoriesRequest
	16, // 11: rpc.NotesService.GetAlgorithmsByCategory:input_type -> rpc.GetAlgorithmsByCategoryRequest
	18, // 12: rpc.NotesService.CreateOrUpdateAlgorithm:input_type -> rpc.CreateOrUpdateAlgorithmRequest
	1,  // 13: rpc.NotesService.GetProblemCategories:output_type -> rpc.GetProblemCategoriesResponse
	3,  // 14: rpc.NotesService.GetProblemsByCategory:output_type -> rpc.GetProblemsByCategoryResponse
	5,  // 15: rpc.NotesService.GetProblemById:output_type -> rpc.GetProblemByIdResponse
	7,  // 16: rpc.NotesService.GetProblemNotesById:output_type -> rpc.GetProblemNotesByIdResponse
	9,  // 17: rpc.NotesService.GetImplementationNotesById:output_type -> rpc.GetImplementationNotesByIdResponse
	11, // 18: rpc.NotesService.CreateOrUpdateProblemDetails:output_type -> rpc.CreateOrUpdateProblemDetailsResponse
	13, // 19: rpc.NotesService.CreateOrUpdateProblemNotes:output_type -> rpc.CreateOrUpdateProblemNotesResponse
	15, // 20: rpc.NotesService.GetAlgorithmCategories:output_type -> rpc.GetAlgorithmCategoriesResponse
	17, // 21: rpc.NotesService.GetAlgorithmsByCategory:output_type -> rpc.GetAlgorithmsByCategoryResponse
	19, // 22: rpc.NotesService.CreateOrUpdateAlgorithm:output_type -> rpc.CreateOrUpdateAlgorithmResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_v1_notes_proto_init() }
func file_rpc_v1_notes_proto_init() {
	if File_rpc_v1_notes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_v1_notes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProblemCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProblemCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProblemsByCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProblemsByCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProblemByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProblemByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProblemNotesByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProblemNotesByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImplementationNotesByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImplementationNotesByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateProblemDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateProblemDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateProblemNotesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateProblemNotesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlgorithmCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlgorithmCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlgorithmsByCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlgorithmsByCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateAlgorithmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_v1_notes_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateAlgorithmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_v1_notes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_v1_notes_proto_goTypes,
		DependencyIndexes: file_rpc_v1_notes_proto_depIdxs,
		MessageInfos:      file_rpc_v1_notes_proto_msgTypes,
	}.Build()
	File_rpc_v1_notes_proto = out.File
	file_rpc_v1_notes_proto_rawDesc = nil
	file_rpc_v1_notes_proto_goTypes = nil
	file_rpc_v1_notes_proto_depIdxs = nil
}
