on:
    pull_request:
        branches:
            - dev
        paths: 
            - "**.go"
name: api

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
    unit-test:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: '1.20'
            - name: install go packages
              run: go mod download
            - name: "run tests"
              run: go test -tags=unit ./api/...
    integration-tests:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: '1.20'
            - name: install go packages
              run: go mod download
            - name: start and load postgres
              run: make up start-etl
            - name: "run integration tests"
              run: go test -tags=integration ./api/...
    
            